In [1]:
import numpy as np

# some of reason numpy is faster than list 
# numpy uses contigious memory
# numpy uses less memory than list
# In list every time we have to check type





In [2]:
# way to create 1-d array

a = np.array([1,2,2])
print(a)



[1 2 2]


In [3]:
# way to create 2-d array
b = np.array([[1,2,3], [1, 1, 1]])
print(b)

[[1 2 3]
 [1 1 1]]


In [4]:
# to get the dimension
print(a.ndim)
print(b.ndim)

# get shape
print(b.shape)

#get data type
print(a.dtype)

# get the size
print(a.itemsize)

# get the total size
print(a.nbytes)

1
2
(2, 3)
int32
4
12


In [5]:
c = np.array([[1, 2, 3, 4, 5, 6,7 ,8 ,9], [10, 11, 12, 13, 14, 15,16, 17, 18]])
print(c)

# get the specific element
print(c[0][8])

 # or you can use [r, c]
print(c[0, 8])

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]
9
9


In [6]:
# to get the specific row
print(c[0][:])

# or simply just c[0]
print(c[0])

# or another way is a[0, :]
print(c[0, :])

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [7]:
# to get the specific column

print(c[:, 0])

[ 1 10]


In [8]:
# getting a little more fancy [startIndex:endIndex:stepsize]
print(c[0,1:-2:2])


[2 4 6]


In [9]:
# to change the entire column
c[:, 2] = [1, 2]

In [10]:
print(c)

[[ 1  2  1  4  5  6  7  8  9]
 [10 11  2 13 14 15 16 17 18]]


In [11]:
# different way to initializing the arrays

# zeors matrix
print("---zeros matrix----")
print(np.zeros(7))

# for multidimesinal
print("\n---multidimension zeroes matrix-----")
print(np.zeros((4, 5)))

# 1's matrix
print("\n---ones matrix----")
print(np.ones(8, dtype='int32'))
print("\n---multidimension ones matrix-----")

print(np.ones((4,4, 2), dtype="int32"))

---zeros matrix----
[0. 0. 0. 0. 0. 0. 0.]

---multidimension zeroes matrix-----
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

---ones matrix----
[1 1 1 1 1 1 1 1]

---multidimension ones matrix-----
[[[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]]


In [12]:
# create matrix with any diffirent numnber
print(np.full((2,2), 100))

[[100 100]
 [100 100]]


In [13]:
# creating a matrix of random decimal numbers
np.random.rand(4,2)

array([[0.3432322 , 0.31538208],
       [0.74859435, 0.42940546],
       [0.01011791, 0.59324982],
       [0.68718587, 0.30277323]])

In [14]:
# creating a matrix of random integer values
# using random.randint(meaximumElement(exclusive), size)
print(np.random.randint(6, size=(3, 3)))

# using random.randint(startElement, meaximumElement(exclusive), size)
np.random.randint(-4, 6, size=(3, 3))

[[1 1 2]
 [3 0 1]
 [2 0 2]]


array([[-2,  2, -4],
       [-1,  5, -2],
       [ 2,  1,  3]])

In [15]:
# identity matrix
np.identity(4, dtype="int32")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [16]:
# some exercise

z = np.ones((5, 5))
print(z)
x = np.zeros((3, 3))
x[1,1] = 9
print(x)

z[1:4, 1:4] = x
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
 # mathematics
    
a = np.array([1,2,3,4])
print(a)

# add 2 to each element of array
a = a+2
print(a)


[1 2 3 4]
[3 4 5 6]


In [18]:
# subtract any number from each element of array
print(a-2)

# same for multiplication and division and power
print(a*2)

print(a/2)

print(a**2)

[1 2 3 4]
[ 6  8 10 12]
[1.5 2.  2.5 3. ]
[ 9 16 25 36]


In [19]:
# make sure that the length of both array should be same
b= np.array([1, 1, 1, 1])
print(a+b)

[4 5 6 7]


In [20]:
# take the sin and cos

print(np.sin(a))
print(np.cos(a))

[ 0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[-0.9899925  -0.65364362  0.28366219  0.96017029]


In [21]:
# linear algerbra
matrix1 = np.full((2,3) , 3, dtype="int32")
print(matrix1)

matrix2 = np.full((3,3) , 3, dtype="int32")
print(matrix2)

# multiplication of two matric
print(np.matmul(matrix1, matrix2))

[[3 3 3]
 [3 3 3]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]
[[27 27 27]
 [27 27 27]]


In [22]:
# find the determinant of matrix
c = np.identity(3)
print(np.linalg.det(c))

1.0


In [23]:
# statistics
mat = np.array([[1, 2, 3], [0, 3, 1]])
print(np.min(mat, axis=0))


[0 2 1]
